# Generated by Django 4.2 on 2023-04-14 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0004_alter_doctor_gender_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medicalphoto',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='prediction',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.CreateModel(
            name='Predicrtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50, verbose_name='Result')),
                ('medicalfile', models.FileField(upload_to='patient/files/', verbose_name='Medical File')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypro.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=50, verbose_name='Result')),
                ('medicalphoto', models.ImageField(upload_to='patient/images/', verbose_name='Medical Photo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypro.patient', verbose_name='Patient')),
            ],
        ),
    ]
