# Generated by Django 4.2 on 2023-04-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro', '0007_classification_isexist_prediction_isexist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientclassification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientprediction',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
